
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;



/**
 *
 * @author RIFAT
 */
public class Search_Item extends javax.swing.JPanel {


    public Search_Item(DataSearch data) {
        initComponents();
        setData(data);
    }
    private void setData(DataSearch data){
        addEventMouse(this);
        addEventMouse(IbText);
        addEventMouse(IbRemove);
        IbText.setText(data.getText());
        if(data.isStory()){
            
            IbText.setForeground(new Color(29,106,205)); 
            IbIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\RIFAT\\Documents\\NetBeansProjects\\Project_updated\\src\\icons8_search_32px.png"));
            IbRemove.setCursor(new Cursor(Cursor.HAND_CURSOR));
        }else{
            IbRemove.setText("");
            
        }
    }
    private void addEventMouse(Component com){
        com.addMouseListener(new MouseAdapter(){
            public void mouseEntered(MouseEvent me){
                setBackground(new Color(215,216,216));
            }
            public void mouseExited(MouseEvent me){
                setBackground(Color.WHITE);
            }
        });
    }   private ActionListener eventClick;
        private ActionListener eventRemove;
        public void addEvent(ActionListener eventClick,ActionListener eventRemove){
            this.eventClick=eventClick;
            this.eventRemove=eventRemove;
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IbIcon = new javax.swing.JLabel();
        IbText = new javax.swing.JLabel();
        IbRemove = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        IbIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\RIFAT\\Documents\\NetBeansProjects\\Project_updated\\src\\home\\icons8_find_and_replace_24px.png")); // NOI18N

        IbText.setText("Text..");
        IbText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IbTextMouseClicked(evt);
            }
        });

        IbRemove.setForeground(new java.awt.Color(204, 204, 204));
        IbRemove.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IbRemove.setText("Remove");
        IbRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IbRemoveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(IbIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(IbText, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IbRemove))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IbRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IbText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 8, Short.MAX_VALUE))
            .addComponent(IbIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void IbRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IbRemoveMouseClicked
        if(!IbRemove.getText().trim().equals("")){
            eventRemove.actionPerformed(null);
        }
    }//GEN-LAST:event_IbRemoveMouseClicked

    private void IbTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IbTextMouseClicked
        eventClick.actionPerformed(null);
    }//GEN-LAST:event_IbTextMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IbIcon;
    private javax.swing.JLabel IbRemove;
    private javax.swing.JLabel IbText;
    // End of variables declaration//GEN-END:variables
}
